# NumPy for Data Science: Comprehensive Guide

**NumPy** (Numerical Python) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these arrays.

---

## 1. Why NumPy Over Python Lists?
* **Speed:** NumPy arrays are stored at one continuous place in memory, allowing for much faster access and manipulation.
* **Vectorization:** Operations are performed on entire arrays at once, removing the need for slow `for` loops.
* **Memory:** NumPy arrays use significantly less space than Python lists.
* **Integration:** It is the foundation for **Pandas, Scikit-learn, and TensorFlow**.

---

## 2. NumPy Array Structure
A NumPy array is a grid of values of the same data type.



* **1D Array:** Single row (Vector).
* **2D Array:** Rows and Columns (Matrix).
* **3D Array:** Multiple 2D arrays (Tensor).

### Array Attributes
* `ndim`: Number of dimensions.
* `shape`: Dimensions of the array (rows, columns).
* `size`: Total number of elements.
* `dtype`: The data type of elements.

---

## 3. Creating Special Arrays
NumPy offers built-in functions to initialize arrays quickly:
* `np.zeros()`: Creates an array filled with 0s.
* `np.ones()`: Creates an array filled with 1s.
* `np.arange()`: Creates a sequence of numbers.
* `np.linspace()`: Creates evenly spaced numbers over a specified interval.

### Random Numbers
Essential for machine learning weight initialization and sampling:
* `np.random.rand()`: Values between 0 and 1.
* `np.random.randn()`: Values from a **Normal Distribution**.
* `np.random.randint()`: Integers within a specific range.

---

## 4. Indexing and Slicing
* **Indexing:** Accessing an element by position (e.g., `arr[0]`).
* **Slicing:** Extracting a portion of an array (e.g., `arr[1:5]`).
* **Multi-dimensional:** Use commas to separate dimensions (e.g., `arr[row, col]`).

---

## 5. Array Operations & Math


* **Vectorization:** Math operations (addition, subtraction, etc.) are applied element-wise.
* **Broadcasting:** A powerful mechanism that allows NumPy to work with arrays of different shapes during arithmetic operations.
* **Statistics:** Built-in functions for `sum()`, `mean()`, `median()`, `std()` (Standard Deviation), and `var()` (Variance).

---

## 6. Shape Manipulation
* **Reshape:** Changes the arrangement of data without changing the data itself.
* **Flatten:** Collapses a multi-dimensional array into a 1D array.
* **Stacking:** * `vstack`: Stack arrays vertically.
    * `hstack`: Stack arrays horizontally.

---

## 7. Data Cleaning & Analysis
* **Filtering:** Use Boolean indexing (e.g., `arr[arr > 5]`) to extract specific data.
* **Unique:** `np.unique()` to find all distinct values.
* **Sorting:** `np.sort()` to order data efficiently.

---

## 8. Memory Management: Copy vs. View
* **View:** A reference to the original array. Modifying a view **changes** the original.
* **Copy:** A physically separate copy of the data. Modifying a copy **does not** change the original.

---

## 🎯 Interview Quick-Hits
* **Speed:** NumPy is faster because it uses C-based arrays.
* **Type:** Arrays must be homogeneous (same data type).
* **Pandas Connection:** A Pandas DataFrame is essentially a collection of NumPy arrays with labels.
* **ML Usage:** All image data and feature matrices are represented as NumPy arrays before training.

In [2]:
import numpy as np

In [3]:
arr = np.array([21,32,43,54])
arr2 = np.array([[21,32,43,54]])
arr3 = np.array([[[12,13,14,15]]])

print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [4]:
ar =  np.array([[23,43,54,],
                [65,76,87],
                [12,13,14]])

print(ar.ndim)
print(ar)

2
[[23 43 54]
 [65 76 87]
 [12 13 14]]


In [5]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
fill = np.full((3,3),9)

print(fill)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [7]:
arange = np.arange(1,20,2)

print(arange)

[ 1  3  5  7  9 11 13 15 17 19]


In [8]:
identity = np.eye(4)

print(identity)
print(identity.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


In [9]:
arr = np.array([[12,13,14,],
                [45,65,76]])

print(arr.shape)
print(arr.size) #number of elements
print(arr.dtype)

(2, 3)
6
int64


In [10]:
arr = np.array([[11.1, 12.2, 13.3],
                [14.4, 15, 16]])

int_arr = arr.astype(int)

print(int_arr.dtype)
print(int_arr.dtype)


int64
int64


In [11]:
arr = np.array([[2,3,4,5]])

print(2 * arr)
print(2 ** arr)

[[ 4  6  8 10]]
[[ 4  8 16 32]]


In [12]:
arr = np.array([[1,2,3,4,5,6,7,8]])

print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.std(arr))
print(np.var(arr))

4.5
8
1
36
2.29128784747792
5.25


In [19]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[5])

6


In [30]:
arr2 = np.array([[1,2,3,4,5,6,7,8]])

print(arr[0:8:1])
print(arr[::-1])#negative slicing
print(arr[:4]) #index 0 to 3
print(arr[1:5]) #index 1 to 4
print(arr[::2]) #every second step

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]
[1 2 3 4]
[2 3 4 5]
[1 3 5 7]


In [43]:
#fencing indexing
fen = np.array([10,15,20,25,30,40,50,60,70,80])

print(fen[[0,2,4]]) #select multiple elements at once

[10 20 30]


In [44]:
print(fen[fen > 1]) #filtering the elements

[10 15 20 25 30 40 50 60 70 80]


In [53]:
#Reshape - only if dimension match
arr = np.array([10,15,20,25,30,40])

reshaped = arr.reshape(3,2)
reshaped1 = arr.reshape(2,3)

print(reshaped)
print('-----')
print(reshaped1)

[[10 15]
 [20 25]
 [30 40]]
-----
[[10 15 20]
 [25 30 40]]


In [55]:
#ravel - view return
#flatten - copy return
arr2 = np.array([[10,15,20],[25,30,40]])

print(arr2.ravel())
print(arr2.flatten())

[10 15 20 25 30 40]
[10 15 20 25 30 40]


In [58]:
arr = np.array([10,15,20,25,30,40])

insert = np.insert(arr,2,35)
print(insert)

[10 15 35 20 25 30 40]


In [65]:
arr2 = np.array([[10,15,20],[25,30,40]])

inserm = np.insert(arr2,2,[4,5,6],axis = 0)

inserm1 = np.insert(arr2,1,[7,8,9],axis = 0)

print(inserm)
print('-----------------')
print(inserm1)

[[10 15 20]
 [25 30 40]
 [ 4  5  6]]
-----------------
[[10 15 20]
 [ 7  8  9]
 [25 30 40]]


In [67]:
arr = np.array([10,20,30])

app = np.append(arr,[40,50,60])

print(app)

[10 20 30 40 50 60]


In [69]:
#np.concatenate(array1,array2) ,axis=0)

arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[6,7,8,9,10]])

concat = np.concatenate((arr1,arr2),axis=0)
print(concat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [70]:
#np.delete(array,index,axis=None)

arr = np.array([[1,2,3,4,5]])

dele = np.delete(arr,0,axis=None)
print(dele)

[2 3 4 5]


In [74]:
arr = np.array([[1,2,3,4,5,6]])

dele = np.delete(arr,1,axis=None)
print(dele)

[1 3 4 5 6]


In [78]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(np.vstack((arr1,arr2)))
print('-------------------------')
print(np.hstack((arr1,arr2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------------------
[ 1  2  3  4  5  6  7  8  9 10]


In [92]:
#np.split - equal split
#npvsplit - vertical split
#np.split - horizontal split
arr = np.array([[1,2,3,4,5,6,7,8,9,10]])

print(np.split(arr, 2, axis=1))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]


In [93]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

np.vsplit(arr, 2)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

In [94]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10]])

print(np.hsplit(arr, 2))


[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]


In [107]:
#with for loop
price = np.array([100,200,300,400,500])
discount = 12

final = []

for prices in price:
    final_price = price - (price * discount/100)
    final.append(final_price)

print(final_price)

[ 88. 176. 264. 352. 440.]


In [108]:
#without for loop
price = np.array([100,200,300,400,500])
discount = 12

final = []

final_price = price - (price * discount/100)
final.append(final_price)

print(final_price)

[ 88. 176. 264. 352. 440.]


In [112]:
#handling missing values
arr = np.array([1,2,np.nan,4,5,np.nan,7,8])

print(np.isnan(arr))

[False False  True False False  True False False]


In [113]:
arr = np.array([1,2,np.nan,4,5,np.nan,7,8])

clean = np.nan_to_num(arr)

print(clean)

[1. 2. 0. 4. 5. 0. 7. 8.]


In [114]:
arr = np.array([1,2,np.inf,4,5,-np.inf,7,8])

print(np.isinf(arr))

[False False  True False False  True False False]


In [117]:
arr = np.array([1,2,np.inf,4,5,-np.inf,7,8])

print(np.isinf(arr))
clean = np.nan_to_num(arr,posinf = 1000,neginf=-10000)
print(clean)

[False False  True False False  True False False]
[ 1.e+00  2.e+00  1.e+03  4.e+00  5.e+00 -1.e+04  7.e+00  8.e+00]


In [118]:
import pandas as pd

In [119]:
df = pd.read_csv('StudentPerformance.csv')

In [120]:
df.head(3)

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0

In [121]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [2]:
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
l = [1,2,3,4,5,6]
print(l)
print(type(l))

[1, 2, 3, 4, 5, 6]
<class 'list'>


Array is faster than list

In [6]:
%timeit [i**5 for i in range(1,10)]

1.08 μs ± 45.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
%timeit  np.arange(1,10)**5

4.45 μs ± 136 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [9]:
x = np.array([[[1,2,3,4,5,6]]])
print(x)
print(type(x))
print(x.ndim)

[[[1 2 3 4 5 6]]]
<class 'numpy.ndarray'>
3


In [10]:
n = []
for i in range(1,5):
    num = input("enter number")
    n.append(num)
print(np.array(n))

y = np.array(n)
print(y)
print(type(n))

enter number 7
enter number 8
enter number 9
enter number 5


['7' '8' '9' '5']
['7' '8' '9' '5']
<class 'list'>


In [11]:
ar2 = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]
2


In [12]:
ar2 = np.array([[1,2,3,4,5,6,7,8],[5,6,7,8,4,5,6,7],[10,11,12,13,1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4  5  6  7  8]
 [ 5  6  7  8  4  5  6  7]
 [10 11 12 13  1  2  3  4]]
2


In [15]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[10,11,12,13],[15,16,17,18]]])
print(ar3)
print(ar3.ndim)
print(type(ar3))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [10 11 12 13]
  [15 16 17 18]]]
3
<class 'numpy.ndarray'>


In [16]:
#multi  dimensional array
arn = np.array([1,2,3,4],ndmin = 15)
print(arn)
print(arn.ndim)

[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]
15


In [19]:
arn = np.array(([1,2,3,4],[5,6,7,8]),ndmin = 15)
print(arn)
print(arn.ndim)

[[[[[[[[[[[[[[[1 2 3 4]
              [5 6 7 8]]]]]]]]]]]]]]]
15


In [20]:
#numpy array with zero
ar = np.zeros(5)
print(ar)
print(ar.ndim)

[0. 0. 0. 0. 0.]
1


In [22]:
ar1 = np.zeros((4,3))
print(ar1)
print(ar1.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [25]:
ar2 = np.zeros((2,3,4))
print(ar2)
print(ar2.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [26]:
#numpy array with all its element 1
arr = np.ones(6)
print(arr)
print(arr.ndim)

[1. 1. 1. 1. 1. 1.]
1


In [27]:
arr1 = np.ones((4,5))
print(arr1)
print(arr1.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2


In [29]:
arr2 = np.ones((1,3,3), dtype = "bool")
print(arr2)
print(arr2.ndim)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
3


In [31]:
#creating an empty array
k = np.empty(3)
print(k)
print(k.ndim)

[0. 0. 0.]
1


In [32]:
d = np.empty((3,3))
print(d)
print(d.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [34]:
#creatin an array with range
b = np.arange(1,21)
print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1


In [35]:
b = np.arange(3,101)
print(b)
print(b.ndim)

[  3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100]
1


In [36]:
b = np.arange(3,101,3)
print(b)
print(b.ndim)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
1


In [37]:
b = np.arange(5,1001,5)
print(b)
print(b.ndim)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

LINSPACE

In [38]:
a = np.linspace(1,10,5)
print(a)
print(a.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
1


In [39]:
a = np.linspace(1,30,8)
print(a)
print(a.ndim)

[ 1.          5.14285714  9.28571429 13.42857143 17.57142857 21.71428571
 25.85714286 30.        ]
1


SHAPE FUNCTION

In [40]:
ar = np.array([[1,2,3],[10,11,12]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[ 1  2  3]
 [10 11 12]]
2
(2, 3)


In [ ]:
ar = np.array([[1,2,3],[10,11,12],[15,16,17]])
print(ar)
print(ar.ndim)
print(ar.shape)

In [45]:
ar = np.array([[[1,2,3],[10,11,12],[15,16,17],[6,7,8]]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[[ 1  2  3]
  [10 11 12]
  [15 16 17]
  [ 6  7  8]]]
3
(1, 4, 3)


RESHAPE

In [48]:
m = np.array([1,2,3,4,5,6,7,8,9,10])
n = m.reshape(2,5)
print(n)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
m = np.array([1,2,3,4,5,6,7,8,9])
n = m.reshape(3,3)
print(n)
print()
print(m)
print()
print(n.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]

2


In [52]:
m = np.array([1,2,3,4,5,6,7,8,9,10])
n = m.reshape(3,3)
print(n)
print()
print(m)
print()
print(n.ndim)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [5]:
m = np.array([1,2,3,4,5,6,7,8,9,10,11,13,12,14,15,16,17,18])
n = m.reshape(3,2,3)
print(n)
print()
print(m)
print()
print(n.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 13]]

 [[12 14 15]
  [16 17 18]]]

[ 1  2  3  4  5  6  7  8  9 10 11 13 12 14 15 16 17 18]

3


In [9]:
m = np.array([1,2,3,4,5,6,7,8,9,10,11,13,12,14,15,16,17,18])
n = m.reshape(3,2,3)
print(n)
print()
print(m)
print()
print(n.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 13]]

 [[12 14 15]
  [16 17 18]]]

[ 1  2  3  4  5  6  7  8  9 10 11 13 12 14 15 16 17 18]

3


In [13]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x.ndim)
print(x)
print()
y = x.reshape(2,1,2,3)
print()
print(y)
print()
print(y.ndim)

2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]]

4


In [16]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print(m.ndim)
n = m.ravel()
print(n)
print(n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[1 2 3 4 5 6 7 8 9]
1


In [17]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print(m.ndim)
n = m.flatten()
print(n)
print(n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[1 2 3 4 5 6 7 8 9]
1


In [20]:
c = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(c)
print(c.ndim)
d = c.flatten()
print(d)

print(d.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4
[1 2 3 4 5 6 7 8 9]
1


In [25]:
#create an array with identity matrix
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
ar1 = np.eye(3,6)
print(ar1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [28]:
#create numpy array with random numbers
#random numbers provide numbers btwn 0 to 1
var = np.random.rand(5)
print(var)

[0.86831903 0.8297737  0.23004162 0.36945211 0.86686106]


In [29]:
var = np.random.rand(3,4)
print(var)

[[0.12455755 0.50448497 0.41760358 0.97879454]
 [0.30731359 0.13763771 0.81471303 0.64622175]
 [0.33310517 0.27657584 0.37491825 0.31265691]]


In [30]:
var = np.random.rand(2,3,4)
print(var)

[[[0.48581955 0.25798865 0.79594578 0.79374653]
  [0.19417749 0.13904715 0.83308857 0.73264377]
  [0.6135792  0.55231915 0.55499418 0.28453903]]

 [[0.08974422 0.12475389 0.04170692 0.69459542]
  [0.18506251 0.82614343 0.16526474 0.01857786]
  [0.49314988 0.75977584 0.36846849 0.59631607]]]


In [33]:
#randn-the functiom=n is used to generate a value close to 0 and may return positive and negative numbers
n = np.random.randn(5)
print(n)
print(n.ndim)

[-0.56415257  0.64304327 -1.44440739  1.02268977 -1.58585476]
1


In [36]:
n = np.random.randn(1,2,5)
print(n)
print(n.ndim)
print(n.shape)

[[[ 1.08078637  0.35904495 -1.17460434  0.43395521 -1.09271589]
  [ 0.07599435  0.21245937 -0.11113829 -0.42508935 -1.43549602]]]
3
(1, 2, 5)


In [41]:
#randint-
a = np.random.randint(4,100,8)
print(a)
print(a.ndim)

[94 69 44 55 69 17 64 77]
1


In [42]:
#randf-
x = np.random.ranf(4)
print(x)

[0.03803067 0.95580368 0.36750771 0.99679706]


In [43]:
x = np.random.ranf((2,4))
print(x)
print(x.ndim)

[[0.4677147  0.54405617 0.4915359  0.36168561]
 [0.27426042 0.80974991 0.95170203 0.45037976]]
2


DATA TYPES IN NUMPY

In [44]:
x = np.array([1,2,3,4])
print(x.dtype)

int64


In [45]:
x1 = np.array([2.5,3.4,5.6,7.8,9.8])
print(x1.dtype)

float64


In [46]:
x2 = np.array(["apple","dog","cherry","ahmed"])
print(x2.dtype)

<U6


In [48]:
x3 = np.array([1,2,2.3,"apple","dog","cherry","ahmed"])
print(x3.dtype)

<U32


In [53]:
#converting data types
x = np.array([1,2,3,4,5])
print(x)
print(x.dtype)

x1 = np.array([1,2,3,4,5], dtype = np.int16)
print(x1)
print(x1.dtype)

[1 2 3 4 5]
int64
[1 2 3 4 5]
int16


In [54]:
x = np.array([1,2,3,4,5])
print(x)
print(x.dtype)

x1 = np.array([1,2,3,4,5], dtype = "f")
print(x1)
print(x1.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float32


In [57]:
m = np.array([1,2,3,4])
print(m)
print(m.dtype)
m1 = np.float64(m)
print(m1)
print(m1.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4.]
float64


In [58]:
m = np.array([1,2,3,4])
print(m)
print(m.dtype)
m1 = np.float64(m)
print(m1)
print(m1.dtype)
m2 = np.int64(m1)
print(m2)
print(m2.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4.]
float64
[1 2 3 4]
int64


In [59]:
x = np.array([1,2,3,4])
y = x.astype(complex)
print(x)
print(x.dtype)
print(y)
print(y.dtype)

[1 2 3 4]
int64
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


In [61]:
#arithmetic operation in numpy arrays
#addition-
x =np.array([1,2,3,4,5])
y = x+3
print(y)

[4 5 6 7 8]


In [62]:
x = np.array([1,2,3,4,5])
m = np.array([5,6,7,8,9])
y = x+m
print(y)

[ 6  8 10 12 14]


In [63]:
x = np.array([1,2,3,4,5])
m = np.array([5,6,7,8,9])
y = np.add(x,m)
print(y)

[ 6  8 10 12 14]


In [64]:
#subtraction-
x =np.array([1,2,3,4,5])
y = x-1
print(y)

[0 1 2 3 4]


In [68]:
x = np.array([11,22,33,34,15])
m = np.array([15,26,17,18,19])
y = m-x
print(y)

[  4   4 -16 -16   4]


In [71]:
x = np.array([11,12,13,14,15])
m = np.array([5,6,7,8,9])
y = np.subtract(x,m)
print(y)

[6 6 6 6 6]


In [72]:
#multiplication-
x =np.array([1,2,3,4,5])
y = x*2
print(y)

[ 2  4  6  8 10]


In [73]:
x = np.array([1,2,3,4,5])
m = np.array([5,6,7,8,9])
y = x*m
print(y)

[ 5 12 21 32 45]


In [75]:
x = np.array([1,2,3,4,5])
m = np.array([5,6,7,8,9])
y = np.multiply(x,m)
print(y)

[ 5 12 21 32 45]


In [76]:
#division-
x =np.array([1,2,3,4,5])
y = x/2
print(y)

[0.5 1.  1.5 2.  2.5]


In [77]:
x = np.array([1,2,3,4,5])
m = np.array([5,6,7,8,9])
y = x/m
print(y)

[0.2        0.33333333 0.42857143 0.5        0.55555556]


In [80]:
#modulus-
x = np.array([10,15,25,30])
y = x%3
print(y)

[1 0 1 0]


In [82]:
x = np.array([12,16,24,32])
m = np.array([7,4,8,23])
y = np.mod(x,m)
print(y)

[5 0 0 9]


In [83]:
#reciprocal-
a = np.array([23,25,28,30])
b = np.reciprocal(a)
print(b)

[0 0 0 0]


arithmetic operation in 2d array

In [84]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])

x = n1+n2
print(x)

[[ 2  4  6  8]
 [10 12 14 16]]


In [85]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])

x = n1-n2
print(x)

[[0 0 0 0]
 [0 0 0 0]]


In [86]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])

x = n1*n2
print(x)

[[ 1  4  9 16]
 [25 36 49 64]]


In [87]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])

x = n1/n2
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Arithmetic operation in 3d array

In [90]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])

x = n1+n2
print(x)
print(x.ndim)

[[[ 2  4  6  8]
  [10 12 14 16]]]
3


In [91]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])

x = n1*n2
print(x)
print(x.ndim)

[[[ 1  4  9 16]
  [25 36 49 64]]]
3


In [92]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])

x = n1/n2
print(x)
print(x.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3


Arithmetic functions

In [94]:
a = np.array([1,2,3,4,56,76,74,56,78,90])
print(np.max(a))
print(np.min(a))

90
1


In [97]:
a = np.array([1,2,3,4,56,76,74,56,78,90,101])
print(np.max(a), np.argmax(a))
print(np.min(a), np.argmin(a))

101 10
1 0


In [99]:
m = np.array([[12,13,14,15,1],[21,32,43,23,45]])
print(m)
print(m.ndim)
n = np.min(m,axis =0)
print(n)

[[12 13 14 15  1]
 [21 32 43 23 45]]
2
[12 13 14 15  1]


In [100]:
m = np.array([[12,13,14,15,1],[21,32,43,23,45]])
print(m)
print(m.ndim)
n = np.min(m,axis =1)
print(n)

[[12 13 14 15  1]
 [21 32 43 23 45]]
2
[ 1 21]


In [101]:
m = np.array([[12,13,14,15,1],[21,32,43,23,45]])
print(m)
print(m.ndim)
n = np.max(m,axis =1)
print(n)

[[12 13 14 15  1]
 [21 32 43 23 45]]
2
[15 45]


In [102]:
m = np.array([[12,13,14,15,1],[21,32,43,23,45]])
print(m)
print(m.ndim)
n = np.max(m,axis =0)
print(n)

[[12 13 14 15  1]
 [21 32 43 23 45]]
2
[21 32 43 23 45]


In [103]:
#sqrt-
a = np.array([12,13,14,15])
print(np.sqrt(a))

[3.46410162 3.60555128 3.74165739 3.87298335]


In [105]:
a = np.array([4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [108]:
a = np.array([[12,13,14,15],[9,64,81,110]])
print(np.sqrt(a))

[[ 3.46410162  3.60555128  3.74165739  3.87298335]
 [ 3.          8.          9.         10.48808848]]


SIN VALUE AND COS VALUE

In [3]:
a = np.array([1,2,3,45])
print(np.sin(a))

[0.84147098 0.90929743 0.14112001 0.85090352]


In [5]:
a = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.98935825  0.41211849 -0.54402111]]


In [6]:
a = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [-0.14550003 -0.91113026 -0.83907153]]


CUMSUM

In [7]:
a = np.array([1,2,3,4])
print(np.cumsum(a))

[ 1  3  6 10]


In [10]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print(np.cumsum(a))

[  1   3   6  10  15  21  28  36  45  55  56  58  61  65  70  76  83  91
 100 110]


BROADCASTING NUMPY ARRAY

In [12]:
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
x = n1+n2
print(x)
print(n1.shape)
print(n2.shape)

[ 6  8 10 12]
(4,)
(4,)


In [17]:
n1 = np.array([1,2,3,4])
print(n1.shape)
print(n1)
print()

n2 = np.array([[1],[2],[3],[4]])
print(n2)
print(n2.shape)
print(n1+n2)

(4,)
[1 2 3 4]

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [25]:
x = np.array([[4],[3]])
print(x.shape)
print(x)
print()

y = np.array([[6,7,3],[1,2,3]])
print(y.shape)
print(y)
print()
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

(2, 1)
[[4]
 [3]]

(2, 3)
[[6 7 3]
 [1 2 3]]

[[10 11  7]
 [ 4  5  6]]

[[-2 -3  1]
 [ 2  1  0]]

[[24 28 12]
 [ 3  6  9]]

[[0.66666667 0.57142857 1.33333333]
 [3.         1.5        1.        ]]


In [32]:
x = np.array([[4,5,6],[3,2,1],[5,6,7]])
print(x.shape)
print(x)
print()

y = np.array([[6,7,1],[1,2,3],[9,8,10]])
print(y.shape)
print(y)
print()

print(x+y)

(3, 3)
[[4 5 6]
 [3 2 1]
 [5 6 7]]

(3, 3)
[[ 6  7  1]
 [ 1  2  3]
 [ 9  8 10]]

[[10 12  7]
 [ 4  4  4]
 [14 14 17]]


INDEXING IN NUMPY ARRAYS

In [35]:
x = np.array([10,11,12,13,14,15])
print(x[5])


15


In [36]:
print(x[-1])

15


In [37]:
print(x[-3])

13


In [39]:
#2D array
x = np.array([[11,12],[13,14]])
print(x[1,0])
print(x[0,0])

13
11


In [41]:

x = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(x[2,2])
print(x[1,2])

3
9


In [9]:
#3D array
x = np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(x.ndim)
print(x)
print(x[1,0,1])

3
[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
16


In [14]:
a = np.array([[[3,6,9],[12,15,18],[1,5,7]]])
print(a)
print(a.ndim)
print(a[0,2,0])

[[[ 3  6  9]
  [12 15 18]
  [ 1  5  7]]]
3
1


In [29]:
#5D Array
a =np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
print(a)
print(a.ndim)
print(a[0,0,0,2,1])

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
5
8


SLICING IN NUMPY ARRAY

In [38]:
#1D Array
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[3:7])
print(a)

[4 5 6 7]
[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
print(a[2:7:2])

[3 5 7]


In [44]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [45]:
a = np.array([12,23,34,45,56,78,76,89,90])
print(a[::-1])

[90 89 76 78 56 45 34 23 12]


In [46]:
b = np.array([12,23,34,45,56,67,78,98,87,76,54])
print(b[3:5])

[45 56]


In [57]:
b = np.array([[11,12,14,15,17,18,19],[21,32,43,54,65,69,89]])
print(b)
print(b[1,1:4])


[[11 12 14 15 17 18 19]
 [21 32 43 54 65 69 89]]
[32 43 54]


In [58]:
b = np.array([[11,12,14,15,17,18,19],[21,32,43,54,65,69,89]])
print(b)
print(b[0,1:4])


[[11 12 14 15 17 18 19]
 [21 32 43 54 65 69 89]]
[12 14 15]


In [62]:
b = np.array([[11,12,14,15,17,18,19],[21,32,43,54,65,69,89]])
print(b)
print(b[1,0:5:2])
print(b[1,::-1])

[[11 12 14 15 17 18 19]
 [21 32 43 54 65 69 89]]
[21 43 65]
[89 69 65 54 43 32 21]


In [72]:
#3D Array
x = np.array([[[11,12,13,1],[14,15,16,2],[17,18,19,3],[20,21,22,4]]])
print(x)
print(x[0,1,1:4])

[[[11 12 13  1]
  [14 15 16  2]
  [17 18 19  3]
  [20 21 22  4]]]
[15 16  2]


In [75]:
print(x[0,2,::2])

[17 19]


In [1]:
import numpy as np

SPLIT ARRAY

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print()
v = np.array_split(a,3)
print(v)
print(type(v))
v[0]
print(v[0])

[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>
[1 2 3]


In [13]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print()
v = np.array_split(a,4, axis = 1)
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int64), array([], shape=(4, 0), dtype=int64)]


In [15]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print()
v = np.array_split(a,2, axis = 0)
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


SEARCH ARRAY

In [17]:
z = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4])
x = np.where(z==3)
print(x)

(array([ 2, 11]),)


In [19]:
z = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4])
x = np.where(z%2==0)
print(x)

(array([ 1,  3,  5,  7, 10, 12]),)


SEARCH SORTED ARRAY

In [23]:
z = np.array([11,12,13,14,15,17,18,19])
x = np.searchsorted(z,16)
print(x)

5


In [32]:
z = np.array([11,12,13,14,15,17,18,19,23,24,25])
x = np.searchsorted(z,20,side ="right")
print(x)

8


In [33]:
p = np.array([21,22,23,31,32,33])
n = np.searchsorted(p,[25,28,30])
print(n)

[3 3 3]


SORT ARRAY

In [36]:
a = np.array([12,13,14,17,87,65,54,43,34,56,78,90,98,97,79,69-1,-34,-54,])
print(np.sort(a))

[-54 -34  12  13  14  17  34  43  54  56  65  68  78  79  87  90  97  98]


In [38]:
b = np.array(["o","a","w","q","t","u","h","n","m","c"])
print(np.sort(b))

['a' 'c' 'h' 'm' 'n' 'o' 'q' 't' 'u' 'w']


In [43]:
a = np.array([[6,5,-1],[6,8,7],[5,6,-2]])
print(a.ndim)
print(a)
print(np.sort(a))

2
[[ 6  5 -1]
 [ 6  8  7]
 [ 5  6 -2]]
[[-1  5  6]
 [ 6  7  8]
 [-2  5  6]]


In [44]:
x = np.array([[[14,18,-9],[-2,36,15],[12,89,-100]]])
print(x)
print()
print(np.sort(x))

[[[  14   18   -9]
  [  -2   36   15]
  [  12   89 -100]]]

[[[  -9   14   18]
  [  -2   15   36]
  [-100   12   89]]]


FILTER ARRAY

In [47]:
a = np.array([11,12,13,14,15,16])
f = [True,False,True,False,False,True]
b = a[f]
print(b)

[11 13 16]


SHUFFLE FUNCTIONS

In [51]:
k = np.array([12,13,14,15,16,17,98,87,76,65])
print(k)
np.random.shuffle(k)
print(k)

[12 13 14 15 16 17 98 87 76 65]
[13 15 16 76 87 98 65 12 14 17]


UNIQUE FUNCTION

In [52]:
k = np.array([12,13,14,15,2,4,7,9,8,32,43,5,8,9,43])
print(k)
x = np.unique(k)
print(x)

[12 13 14 15  2  4  7  9  8 32 43  5  8  9 43]
[ 2  4  5  7  8  9 12 13 14 15 32 43]


In [53]:
k = np.array([12,13,14,15,2,4,7,9,8,32,43,5,8,9,43])
print(k)
x = np.unique(k,return_index = True)
print(x)

[12 13 14 15  2  4  7  9  8 32 43  5  8  9 43]
(array([ 2,  4,  5,  7,  8,  9, 12, 13, 14, 15, 32, 43]), array([ 4,  5, 11,  6,  8,  7,  0,  1,  2,  3,  9, 10]))


In [55]:
k = np.array([12,13,14,15,2,4,7,9,8,32,43,5,8,9,43,2,2])
print(k)
x = np.unique(k,return_index = True,return_counts = True)
print(x)

[12 13 14 15  2  4  7  9  8 32 43  5  8  9 43  2  2]
(array([ 2,  4,  5,  7,  8,  9, 12, 13, 14, 15, 32, 43]), array([ 4,  5, 11,  6,  8,  7,  0,  1,  2,  3,  9, 10]), array([3, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2]))


RESIZE FUNCTION

In [61]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.ndim)
print(a.shape)
b = np.resize(a,(4,2))
print("now the size is")
print(b)
print("the dimension is", b.ndim)
print("the shape is", b.shape)

[1 2 3 4 5 6 7 8 9]
1
(9,)
now the size is
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
the dimension is 2
the shape is (4, 2)


INSERT FUNCTION

In [63]:
n = np.array([1,2,3,4,5,6,7,8,9])
print(n)
v = np.insert(n,3,200)
print(v)

[1 2 3 4 5 6 7 8 9]
[  1   2   3 200   4   5   6   7   8   9]


In [65]:
n = np.array([1,2,3,4,5,6,7,8,9])
print(n)
v = np.insert(n,(3,5,6),(200,40,20))
print(v)

[1 2 3 4 5 6 7 8 9]
[  1   2   3 200   4   5  40   6  20   7   8   9]


2D ARRAY

In [67]:
x = np.array([[2,7,9,6,5],[4,5,6,7,8]])
print(x)
print()
x1 = np.insert(x,2,24,axis =1)
print(x1)

[[2 7 9 6 5]
 [4 5 6 7 8]]

[[ 2  7 24  9  6  5]
 [ 4  5 24  6  7  8]]


In [68]:
x = np.array([[2,7,9,6,5],[4,5,6,7,8]])
print(x)
print()
x1 = np.insert(x,2,24,axis =0)
print(x1)

[[2 7 9 6 5]
 [4 5 6 7 8]]

[[ 2  7  9  6  5]
 [ 4  5  6  7  8]
 [24 24 24 24 24]]


In [69]:
x = np.array([[2,7,9,6,5],[4,5,6,7,8]])
print(x)
print()
x1 = np.insert(x,2,[24,25,26,27,28], axis =0)
print(x1)

[[2 7 9 6 5]
 [4 5 6 7 8]]

[[ 2  7  9  6  5]
 [ 4  5  6  7  8]
 [24 25 26 27 28]]


APPEND

In [71]:
a = np.array([12,13,14,15])
x = np.append(a,1.6)
print(x)

[12.  13.  14.  15.   1.6]


In [78]:
x = np.array([[2,7,9,6,5],[4,5,6,7,8]])
print(x)
print()
x1 = np.append(x, [[23,34,45,-54,-65]] ,axis=0)
print(x1)

[[2 7 9 6 5]
 [4 5 6 7 8]]

[[  2   7   9   6   5]
 [  4   5   6   7   8]
 [ 23  34  45 -54 -65]]


DELETE

In [79]:
a = np.array([12,13,14,15])
print(a)
print()
d = np.delete(a,[1])
print(d)

[12 13 14 15]

[12 14 15]


In [81]:
x = np.array([[2,7,9,6,8],[4,5,6,7,8],[9,8,7,6,5]])
print(x)
print()
m = np.delete(x,0,axis =0)
print(m)

[[2 7 9 6 8]
 [4 5 6 7 8]
 [9 8 7 6 5]]

[[4 5 6 7 8]
 [9 8 7 6 5]]


MATRIX

In [2]:
import numpy as np

In [5]:
a = np.matrix([[1,2,3],[1,2,3]])
print(a)
print(type(a))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


ARITHMETIC OPERATIONS IN MATRIX

In [8]:
a = np.matrix([[1,2,3],[1,2,3]])
c = np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print()
print(a+c)
print("we are talking about array")
n = np.array([[1,2,3]])
m = np.array([[4,5,6],[4,5,6]])
print(n)
print()
print(m)
print()
print(m+n)

[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[5 7 9]
 [5 7 9]]
we are talking about array
[[1 2 3]]

[[4 5 6]
 [4 5 6]]

[[5 7 9]
 [5 7 9]]


In [9]:
a = np.matrix([[1,2,3],[1,2,3]])
c = np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print()
print(a-c)
print("we are talking about array")
n = np.array([[1,2,3]])
m = np.array([[4,5,6],[4,5,6]])
print(n)
print()
print(m)
print()
print(m-n)


[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[-3 -3 -3]
 [-3 -3 -3]]
we are talking about array
[[1 2 3]]

[[4 5 6]
 [4 5 6]]

[[3 3 3]
 [3 3 3]]


In [13]:
print("we are talkimg about matrix")
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
print(a)
print()
print(b)
print()
l = a.dot(b)
print(l)
print("we are talkimg about array")
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])
print(m)
print()
print(n)
print()
print(m*n)

we are talkimg about matrix
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]
we are talkimg about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


In [15]:
print("we are talkimg about matrix")
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
print(a)
print()
print(b)
print()
print(b/a)
print("we are talkimg about array")
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])
print(m)
print()
print(n)
print()
print(n/m)

we are talkimg about matrix
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[5.         3.        ]
 [2.33333333 2.        ]]
we are talkimg about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[5.         3.        ]
 [2.33333333 2.        ]]


MATRIX  TRANSPOSE FUNCTIONS

In [18]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(np.transpose(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [21]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(np.swapaxes(a,1,0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(np.swapaxes(a,0,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


INVERSE


In [25]:
a = np.matrix([[3,4],[5,6]])
print(a)
print()
print(np.linalg.inv(a))

[[3 4]
 [5 6]]

[[-3.   2. ]
 [ 2.5 -1.5]]


POWER

In [28]:
a = np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.matrix_power(a,2))
print()
print(np.linalg.matrix_power(a,0))
print()
print(np.linalg.matrix_power(a,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [30]:
a = np.matrix([[1,2,7],[9,3,4],[10,11,13]])
print(a)
print()
print(np.linalg.det(a))

[[ 1  2  7]
 [ 9  3  4]
 [10 11 13]]

323.9999999999999


In [2]:
import numpy as np

In [4]:
#number from 10 to 51
num = np.arange(10,51)

print(num)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
#Identity matrix
eye = np.eye(3)

print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#Random integers
random = np.random.rand(1,100,25)

print(random)

[[[0.65532271 0.72422895 0.39211356 ... 0.3772837  0.64523039 0.23328592]
  [0.79722169 0.36728528 0.35302083 ... 0.01636521 0.57468426 0.19938591]
  [0.69604727 0.58523383 0.60271413 ... 0.7265992  0.31017878 0.36806076]
  ...
  [0.48283885 0.63053159 0.85888865 ... 0.77411177 0.71483089 0.23759147]
  [0.33652997 0.31573724 0.24179862 ... 0.08277493 0.83999913 0.35842036]
  [0.87489788 0.93111973 0.15286186 ... 0.29264288 0.5252693  0.88464685]]]


In [16]:
arr = np.array([1,2,3,4,5,6,7,8])

print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))

8
1
4.5
2.29128784747792


In [20]:
#Converting list to array
lst = [1,2,3,4,5]

arr = np.array(lst,dtype=float)

print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [30]:
#Reshaping the array
reshaped = np.arange(0,12).reshape(3,4)

print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
#Values greater than mean
arr = np.array([[1,2,3,],[4,5,6],[7,8,9]])

print(arr > arr.mean())

[[False False False]
 [False False  True]
 [ True  True  True]]


In [39]:
#Vstack and Hstack
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(np.vstack((arr1,arr2)))
print('------------------------------------')
print(np.hstack((arr1,arr2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
#argmax - Gives max index
arr = np.array([1,2,3,4,5])

print(np.argmax(arr))

4


In [49]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.sum(axis=1)) #Rows
print(arr.sum(axis=0)) # Columns

[ 6 15 24]
[12 15 18]


In [50]:
#Intersection
np.intersect1d([1,2,3], [2,3,4])


array([2, 3])

In [57]:
#Removes rows of Nan

arr = np.array([[1,2,3],[4,np.nan,5],[6,7,np.nan]])

fill = arr[~np.isnan(arr).any(axis=1)]

print(fill)

[[1. 2. 3.]]


In [58]:
#Sort by second value
arr = np.array([[1,3],[2,1],[3,2]])
arr[arr[:,1].argsort()]

array([[2, 1],
       [3, 2],
       [1, 3]])